services:
  - type: web
    name: ims
    runtime: docker
    plan: free
    dockerfilePath: ./IMS/Dockerfile
    dockerContext: ./IMS
    healthCheckPath: /
  - type: web
    name: group-management
    runtime: docker
    plan: free
    dockerfilePath: ./Task 2/Dockerfile
    dockerContext: ./Task 2
    healthCheckPath: /
  - type: web
    name: task-3-group-management
    runtime: docker
    plan: free
    dockerfilePath: ./Task 3/Dockerfile
    dockerContext: ./Task 3
    healthCheckPath: /